# local ubuntu microk8s deployment
# https://matthewpalmer.net/kubernetes-app-developer/articles/kubernetes-apiversion-definition-guide.html
# apiVersion: extensions/v1beta1 to apps/v1
# https://stackoverflow.com/questions/58481850/no-matches-for-kind-deployment-in-version-extensions-v1beta1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-demo-svc-deployment
spec:
  selector:
    matchLabels:
      app: springboot-demo-svc
      env: dev
  replicas: 1
  template:
    metadata:
      labels:
        app: springboot-demo-svc
        env: dev
    spec:
      containers:
      - name: springboot-demo-svc
        image: localhost:5000/greatwqs/springboot-demo
        imagePullPolicy: IfNotPresent
        ports:
        - name: http-port
          containerPort: 8080
        env:
        - name: spring.profiles.active
          value: "dev"
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-demo-svc
spec:
  selector:
    app: springboot-demo-svc
    env: dev
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080